### ISSUE TITLE
Account info

### ISSUE THREAD

**Issue by furlongi** [anime-crossing/man-chan#12]
Similar to our old bot, we share some of our account info for ~~leeching~~ sharing purposes.

Of course make this secure. Have the info stored locally as a json and loaded in. Challenge will be formatting since message text is dynamically created instead of statically. Also for security, can only be used on specific servers

**Comment by ssumachai** [comment]
Added basic functionality, still need to improve and add drop down options

**Comment by ssumachai** [comment]
Need to make it so that only the author can access button
