### ISSUE TITLE
AniList Integration

### ISSUE THREAD

**Issue by furlongi** [anime-crossing/man-chan#6]
https://anilist.gitbook.io/anilist-apiv2-docs/

We want to retrieve info on our favorite anime. Most of us use AniList, which luckily has an API (and with very good documentation).
Anilist uses [graphql](https://graphql.org/) so take a peek in it. Anilist also has a [playground](https://anilist.co/graphiql) to test your post requests.

Commands:
- setup: link an account to our database. For example: !setup [username]  This will ask the user to confirm if it is their account. If yes, store any info needed into our database so we can retrieve that user's anilist info.
- anime: given a name of an anime, get info on it
![image](https://user-images.githubusercontent.com/29317938/165500801-6b166cc1-644a-44ab-93e0-d6093bf513be.png)
If the user is registered, then send additional info back on their stats such as rating. The anime title should be a clickable link. Command should work with either 'anime' or 'ani' as an alias
- manga: same as above but for manga. Note that light novels are under the manga category but tagged differently. so make a novel command too that differentiates. Commands and aliases should be "manga" or "man", "novel" or "nov"
- lb: shows stat leaderboard of all people registered in the guild (server). Order by two categories: hours/days watched and pages read

You will need to create tables that can fit all this information and learn how to make http requests for the api. We will be using sqlalchemy and alembic to interact with the database. I will look for a library for the http requests but if you find one then let me know.

**Comment by ssumachai** [comment]
I do a start after crimmas

**Comment by ssumachai** [comment]
Created initial embed, might have to make it a class method for the selection.

- Having the command create my buttons from scratch is fine when just one command, `anime` is implmented, but if i have two commands, such as `manga`, it may be easier to just create a `Button` class object or something.  Not 100% on verbiage but i have an idea of what to do.

Still need to add aliases to commands, will do eventually

**Comment by ssumachai** [comment]
Got API requests to work, `anime` integrated with alias `ani`.  Still need to do `manga`.  Once `anime` and `manga` both work, using either function will invoke a selection menu, similar to how Karuta does `lookup`

**Comment by ssumachai** [comment]
implemented `manga` (alias `man`) and `novel` (alias `nov`).  Had to subsequently deprecate original `man` greeting command.  User Information next, utilizing SQLAlchemy and Alembic to keep userID and Anilist Profile

**Comment by ssumachai** [comment]
<img width="556" alt="image" src="https://user-images.githubusercontent.com/49208740/210110321-3b12b9c7-217a-419d-a8e9-e9ee38ad12f9.png">

**Comment by ssumachai** [comment]
Actually scratch that, search embed is next, similar to how karuta does klu
<img width="378" alt="image" src="https://user-images.githubusercontent.com/49208740/210110411-f93aa492-92d2-4c10-8969-8ec635767637.png">

**Comment by ssumachai** [comment]
@furlongi how would you like the search parameters to be presented?

Anime name (in bold) * Studio, is my suggestion

**Comment by ssumachai** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/49208740/210115922-c5509738-79f4-44c8-aafb-767791a379a7.png">

<img width="319" alt="image" src="https://user-images.githubusercontent.com/49208740/210115925-3a88bf8e-9ed1-4fd8-a095-ef27f840c6d3.png">

**Comment by ssumachai** [comment]
DB Works!! I do however, need to clean up code immensely, as well as adding edge cases for the database, example if you already have an account linked

**Comment by ssumachai** [comment]
Just need to fix description with regex
